platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode 10 caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'TestPlugin', :path => '../../test-plugin'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
#    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'SwiftLocation', '~> 4.2.0'
    pod 'SwiftEventBus', :tag => '5.0.1', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
  #  pod 'Alamofire', '~> 5.2'
  #  pod 'AlamofireImage', '~> 4.1'
  #  pod 'Alamofire', '~> 4.4'
  #  pod 'AlamofireImage', '~> 3.1'
    pod 'SwiftyJSON'
end
